_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
env_id:
    value: CartPole-v0
exp:
    value: base
gamma:
    value: 0.99
lr:
    value: 0.001
project:
    value: Actor-Critic
seed:
    value: 1
total_episodes:
    value: 1000
track:
    value: true
